/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.reserva;

/**
 *
 * @author Usuario
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoInicio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        texto1 = new javax.swing.JLabel();
        TxtReserva = new javax.swing.JLabel();
        DescripcionRv = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoInicio.setText("Inicio");
        add(textoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 700, -1));

        texto1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texto1.setText("Seleccione la opcion que desee realizar.");
        add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 640, 50));

        TxtReserva.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TxtReserva.setText("Reservar");
        add(TxtReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 430, 50));

        DescripcionRv.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DescripcionRv.setText("En esta opcion encontrara el panel para reservar la boleteria de la pelicula.");
        add(DescripcionRv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 540, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Tarjeta UQ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("En esta opcion podra optar por obtener la tarjeta UQ.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 520, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Confiteria");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 50));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("En esta opcion podra comprar su confiteria.");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 480, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescripcionRv;
    private javax.swing.JLabel TxtReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel textoInicio;
    // End of variables declaration//GEN-END:variables
}
