/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.reserva;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class PanelRegistro extends javax.swing.JPanel {

    static ArrayList<String>ArrayListNombre;
    static ArrayList<String>ArrayListIdentificacion;
    static ArrayList<String>ArrayListContraseña;

    
    public PanelRegistro() {
        initComponents();
        ArrayListNombre = new ArrayList<>();
        ArrayListIdentificacion = new ArrayList<>();
        ArrayListContraseña = new ArrayList<>();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegistro = new javax.swing.JPanel();
        nombreUsuarioTxt = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        identificacionTxt = new javax.swing.JLabel();
        Identificacion = new javax.swing.JTextField();
        contraseñaTxt = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        Registrarme = new javax.swing.JPanel();
        registrarmeTxt = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelRegistro.setBackground(new java.awt.Color(255, 255, 255));

        nombreUsuarioTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombreUsuarioTxt.setText("Nombre de Usuario");

        identificacionTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        identificacionTxt.setText("Identificacion");

        contraseñaTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        contraseñaTxt.setText("Contraseña");

        Registrarme.setBackground(new java.awt.Color(153, 153, 153));
        Registrarme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        registrarmeTxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        registrarmeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarmeTxt.setText("Registrarme");
        registrarmeTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarmeTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarmeTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarmeTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RegistrarmeLayout = new javax.swing.GroupLayout(Registrarme);
        Registrarme.setLayout(RegistrarmeLayout);
        RegistrarmeLayout.setHorizontalGroup(
            RegistrarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarmeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrarmeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        RegistrarmeLayout.setVerticalGroup(
            RegistrarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrarmeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelRegistroLayout = new javax.swing.GroupLayout(PanelRegistro);
        PanelRegistro.setLayout(PanelRegistroLayout);
        PanelRegistroLayout.setHorizontalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroLayout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroLayout.createSequentialGroup()
                        .addComponent(nombreUsuarioTxt)
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroLayout.createSequentialGroup()
                        .addComponent(Registrarme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(identificacionTxt)
                .addGap(306, 306, 306))
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(contraseñaTxt)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelRegistroLayout.setVerticalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(nombreUsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(identificacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contraseñaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(Registrarme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        add(PanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void registrarmeTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarmeTxtMouseClicked

        int j, cont=0;
        for (j=0;j<ArrayListIdentificacion.size();j++){
            if (Identificacion.getText().equals(ArrayListIdentificacion.get(j))){
                cont+=1;
            }
        }
        if (cont==0){
            if (nombreUsuario.getText().isEmpty()||Identificacion.getText().isEmpty()||contraseña.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Llene los campos en blanco");
            }else {
                ArrayListNombre.add(nombreUsuario.getText());
                ArrayListIdentificacion.add(Identificacion.getText());
                ArrayListContraseña.add(contraseña.getText());
                JOptionPane.showMessageDialog(null,"Registrado");
                nombreUsuario.setText("");
                Identificacion.setText("");
                contraseña.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "ya existe otro usuario registrado con la misma edentificacion");
            nombreUsuario.setText("");
            Identificacion.setText("");
            contraseña.setText("");
        }

    }//GEN-LAST:event_registrarmeTxtMouseClicked

    private void registrarmeTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarmeTxtMouseEntered
        Registrarme.setBackground(new Color(51,102,255));
        registrarmeTxt.setForeground(Color.white);

    }//GEN-LAST:event_registrarmeTxtMouseEntered

    private void registrarmeTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarmeTxtMouseExited
        Registrarme.setBackground(new Color (153,153,153));
        registrarmeTxt.setForeground(Color.black);
    }//GEN-LAST:event_registrarmeTxtMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Identificacion;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JPanel Registrarme;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel contraseñaTxt;
    private javax.swing.JLabel identificacionTxt;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JLabel nombreUsuarioTxt;
    private javax.swing.JLabel registrarmeTxt;
    // End of variables declaration//GEN-END:variables
}
