/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.reserva;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;


public class PanelIngreso extends javax.swing.JPanel {
    
    Login lgg;
    Reserva pr;
    public static Date fechaActual = new Date();
    public static SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
    public float valorComprado;
    
    public PanelIngreso(Login lg) {
        initComponents();
        lgg = lg;
        pr = new Reserva();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        NombreUsuarioTxt = new javax.swing.JLabel();
        PIUsuario = new javax.swing.JTextField();
        identificacionTxt = new javax.swing.JLabel();
        PIIdentificacion = new javax.swing.JTextField();
        contraseñaTxt = new javax.swing.JLabel();
        PIContraseña = new javax.swing.JPasswordField();
        ButtonIngresar = new javax.swing.JPanel();
        IngresarTxt = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        NombreUsuarioTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NombreUsuarioTxt.setText("Nombre de Usuario");

        PIUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        identificacionTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        identificacionTxt.setText("Identificación");

        PIIdentificacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        contraseñaTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        contraseñaTxt.setText("Contraseña");

        ButtonIngresar.setBackground(new java.awt.Color(153, 153, 153));

        IngresarTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngresarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IngresarTxt.setText("Ingresar");
        IngresarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IngresarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IngresarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ButtonIngresarLayout = new javax.swing.GroupLayout(ButtonIngresar);
        ButtonIngresar.setLayout(ButtonIngresarLayout);
        ButtonIngresarLayout.setHorizontalGroup(
            ButtonIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IngresarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        ButtonIngresarLayout.setVerticalGroup(
            ButtonIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IngresarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(NombreUsuarioTxt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(identificacionTxt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(contraseñaTxt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PIUsuario)
                            .addComponent(PIIdentificacion)
                            .addComponent(PIContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(ButtonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(NombreUsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(identificacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PIIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contraseñaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PIContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ButtonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarTxtMouseEntered
        ButtonIngresar.setBackground(new Color(51,102,255));
        IngresarTxt.setForeground(Color.white);
    }//GEN-LAST:event_IngresarTxtMouseEntered

    private void IngresarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarTxtMouseExited
         ButtonIngresar.setBackground(new Color (153,153,153));
        IngresarTxt.setForeground(Color.black);
    }//GEN-LAST:event_IngresarTxtMouseExited

    private void IngresarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarTxtMouseClicked
        
        if (PIUsuario.getText().isEmpty()||PIContraseña.getText().isEmpty()||PIIdentificacion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "llene los campos en blanco");
        }
        int x, index=-1;
        for (x=0;x<PanelRegistro.ArrayListIdentificacion.size();x++){
            if (PanelRegistro.ArrayListIdentificacion.get(x).equals(PIIdentificacion.getText())){
                index = x;
            }
            else{
                JOptionPane.showMessageDialog(null, "no existe un usuario registrado con la identificacion suministrada");
            }
        }
        if (PIUsuario.getText().equals(PanelRegistro.ArrayListNombre.get(index))){
            if (PIContraseña.getText().equals(PanelRegistro.ArrayListContraseña.get(index))){
                
                lgg.setVisible(false);
                pr.setVisible(true);
                ArrayList<String>ArrayListTemporal = new ArrayList<>();
                ArrayListTemporal.add(""+PIIdentificacion.getText());
                ArrayListTemporal.add(fecha.format(fechaActual));
                
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos");
        }
    }//GEN-LAST:event_IngresarTxtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonIngresar;
    private javax.swing.JLabel IngresarTxt;
    private javax.swing.JLabel NombreUsuarioTxt;
    private javax.swing.JPasswordField PIContraseña;
    private javax.swing.JTextField PIIdentificacion;
    private javax.swing.JTextField PIUsuario;
    private javax.swing.JLabel contraseñaTxt;
    private javax.swing.JLabel identificacionTxt;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
