/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.reserva;

import java.awt.BorderLayout;
import javax.swing.JPanel;


public class Reserva extends javax.swing.JFrame {
    Login lg = new Login ();
    static boolean tarjetaUQ;
    public Reserva() {
        initComponents();
        Inicio pl = new Inicio();
        ShowPanel(pl);
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Pvariable = new javax.swing.JPanel();
        Pbotones = new javax.swing.JPanel();
        BotonInicio = new javax.swing.JButton();
        botonReserva = new javax.swing.JButton();
        BotonPagoTarjeta = new javax.swing.JButton();
        confiteria = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        logoCine = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 550));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(950, 550));
        bg.setMinimumSize(new java.awt.Dimension(950, 550));
        bg.setPreferredSize(new java.awt.Dimension(950, 550));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pvariable.setBackground(new java.awt.Color(255, 255, 255));
        Pvariable.setMinimumSize(new java.awt.Dimension(0, 0));
        Pvariable.setPreferredSize(new java.awt.Dimension(750, 550));

        javax.swing.GroupLayout PvariableLayout = new javax.swing.GroupLayout(Pvariable);
        Pvariable.setLayout(PvariableLayout);
        PvariableLayout.setHorizontalGroup(
            PvariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        PvariableLayout.setVerticalGroup(
            PvariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        bg.add(Pvariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 710, 550));

        Pbotones.setBackground(new java.awt.Color(51, 102, 255));
        Pbotones.setPreferredSize(new java.awt.Dimension(240, 550));

        BotonInicio.setBackground(new java.awt.Color(51, 102, 255));
        BotonInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonInicio.setForeground(new java.awt.Color(255, 255, 255));
        BotonInicio.setText("Inicio");
        BotonInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotonInicio.setBorderPainted(false);
        BotonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        botonReserva.setBackground(new java.awt.Color(51, 102, 255));
        botonReserva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonReserva.setForeground(new java.awt.Color(255, 255, 255));
        botonReserva.setText("Reservar");
        botonReserva.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservaActionPerformed(evt);
            }
        });

        BotonPagoTarjeta.setBackground(new java.awt.Color(51, 102, 255));
        BotonPagoTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonPagoTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        BotonPagoTarjeta.setText("Tarjeta UQ");
        BotonPagoTarjeta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotonPagoTarjeta.setBorderPainted(false);
        BotonPagoTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPagoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPagoTarjetaActionPerformed(evt);
            }
        });

        confiteria.setBackground(new java.awt.Color(51, 102, 255));
        confiteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confiteria.setForeground(new java.awt.Color(255, 255, 255));
        confiteria.setText("Confiteria");
        confiteria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        confiteria.setBorderPainted(false);
        confiteria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confiteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confiteriaActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 102, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("jButton4");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 102, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("jButton5");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        logoCine.setText("jLabel1");

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PbotonesLayout = new javax.swing.GroupLayout(Pbotones);
        Pbotones.setLayout(PbotonesLayout);
        PbotonesLayout.setHorizontalGroup(
            PbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PbotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(PbotonesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logoCine, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(PbotonesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(confiteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonPagoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(botonReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PbotonesLayout.setVerticalGroup(
            PbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PbotonesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(logoCine, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(BotonInicio)
                .addGap(24, 24, 24)
                .addComponent(botonReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonPagoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confiteria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        bg.add(Pbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // esta funcion se encarga de cambiar el panel
    private void ShowPanel(JPanel p){
        p.setSize(750, 550);
        p.setLocation(0, 0);
        Pvariable.removeAll();
        Pvariable.add(p, BorderLayout.CENTER);
        Pvariable.revalidate();
        Pvariable.repaint();
    }
    private void botonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservaActionPerformed
        panelReserva pl = new panelReserva();
        ShowPanel(pl);
    }//GEN-LAST:event_botonReservaActionPerformed

    private void confiteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confiteriaActionPerformed
        PanelConfiteria p1 = new PanelConfiteria();
        ShowPanel(p1);
    }//GEN-LAST:event_confiteriaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BotonPagoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPagoTarjetaActionPerformed
        tarjetaUQ pl = new tarjetaUQ();
        ShowPanel(pl);
    }//GEN-LAST:event_BotonPagoTarjetaActionPerformed

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        Inicio pl = new Inicio();
        ShowPanel(pl);
    }//GEN-LAST:event_BotonInicioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton BotonPagoTarjeta;
    private javax.swing.JPanel Pbotones;
    private javax.swing.JPanel Pvariable;
    private javax.swing.JPanel bg;
    private javax.swing.JButton botonReserva;
    private javax.swing.JButton confiteria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoCine;
    // End of variables declaration//GEN-END:variables
}
