/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.reserva;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class Tarjeta extends javax.swing.JPanel {
    static ArrayList<String>copiaNombre = new ArrayList<String>();
    static ArrayList<String>copiaIdentificacion = new ArrayList<String>();
    static ArrayList<String>numeroTarjeta = new ArrayList<String>();
    static ArrayList<String>AlmacenarDatos = new ArrayList<String>();
    //boolean tarjetaUQ = false;
    String numeroIdentificacion;
    public Tarjeta() {
        initComponents();
        copiaNombre = copiar(copiaNombre);
        copiaIdentificacion = copiar(copiaIdentificacion);
    }
    
    
    private static ArrayList copiar(ArrayList b){
        ArrayList<String> copia = new ArrayList <String>();
        int i, x;
        x = PanelRegistro.ArrayListNombre.size();
        for(i=0;i<x;i++){
            if(b == copiaNombre){
            copia.add(PanelRegistro.ArrayListNombre.get(i));    
            }
            else if (b == copiaIdentificacion){
            copia.add(PanelRegistro.ArrayListIdentificacion.get(i));  
            }    
        }
        return copia;
    }
    private void Validacion (){
        if(Reserva.tarjetaUQ){
            JOptionPane.showMessageDialog(null, "Usted ya es poseedor de la tarjeta UQ");
        }    
        else{
            String opcion = TarjetasOPC.getSelectedItem().toString();
            numeroIdentificacion = copiaIdentificacion.get(0);
            if("Tarjeta UQ Basic".equals(opcion)){
                Reserva.tarjetaUQ = true;
                numeroTarjeta.add(numeroIdentificacion);
                JOptionPane.showMessageDialog(null, "Gracias por adquirir la tarjeta del cine UQ");
            }
            else if("Tarjeta UQ Gold".equals(opcion)){
                JOptionPane.showMessageDialog(null, "Esta opcion no es adquirible");
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TarjetasOPC = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione la tarjeta a solicitar.");

        TarjetasOPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta UQ Basic", "Tarjeta UQ Gold" }));
        TarjetasOPC.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TarjetasOPCComponentRemoved(evt);
            }
        });
        TarjetasOPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetasOPCActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 105, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TarjetasOPC, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jButton1)))
                .addGap(0, 250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TarjetasOPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addContainerGap(302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TarjetasOPCComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TarjetasOPCComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TarjetasOPCComponentRemoved

    private void TarjetasOPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetasOPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TarjetasOPCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Validacion();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TarjetasOPC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
